const fs = require('fs');
const c = fs.readFileSync('D:\\loksewa-portal\\app.html', 'utf8');
console.log('tab-revision:', (c.match(/tab-revision/g) || []).length);
console.log('nav-revision:', (c.match(/nav-revision/g) || []).length);
console.log('revision-container:', (c.match(/revision-container/g) || []).length);
console.log('switchTab(revision):', (c.match(/switchTab\('revision'\)/g) || []).length);
console.log('+100 XP:', (c.match(/\+100 XP/g) || []).length);
console.log('-20 XP:', (c.match(/-20 XP/g) || []).length);
console.log('clearWeakPoints:', (c.match(/clearWeakPoints/g) || []).length);
console.log('renderRevisionMCQs:', (c.match(/renderRevisionMCQs/g) || []).length);