const fs = require('fs');
const c = fs.readFileSync('D:\\loksewa-portal\\app.html', 'utf8');
console.log('liveSearch:', (c.match(/oninput="liveSearch/g) || []).length);
console.log('status-select:', (c.match(/id="status-select"/g) || []).length);
console.log('mastery-select:', (c.match(/id="mastery-select"/g) || []).length);
console.log('sort-select:', (c.match(/id="sort-select"/g) || []).length);
console.log('openStudyCard:', (c.match(/onclick="openStudyCard/g) || []).length);
console.log('search-suggestions:', (c.match(/search-suggestions/g) || []).length);
console.log('Bronze:', (c.match(/Bronze/g) || []).length);
console.log('Silver:', (c.match(/Silver/g) || []).length);
console.log('Gold:', (c.match(/Gold/g) || []).length);
console.log('Platinum:', (c.match(/Platinum/g) || []).length);
console.log('Diamond:', (c.match(/Diamond/g) || []).length);