/**
 * Remote question-bank configuration (Option C — auto-updating bank).
 *
 * The repo's CI (`.github/workflows/ci.yml`) publishes the whole repo root to
 * GitHub Pages, so `question-bank.json` (mobile manifest with per-file SHA-256
 * hashes) and `questions/*.json` are reachable at the production URL below.
 * The mobile app checks THIS location on boot and applies a remote bank
 * whenever the manifest hash differs from the installed one.
 *
 * `question-bank.json` is generated by:
 *   node scripts/generate-question-bank-manifest.js
 * (the web app's `manifest.json` — a plain list of paths — is unchanged).
 *
 * To switch environments (e.g. a private staging CDN), change this value — it
 * must end with a trailing slash and serve `question-bank.json` at its root.
 */
export const QUESTION_BANK_BASE_URL = 'https://rbc1740-sys.github.io/loksewa-portal/';

/** Remote bank manifest filename (contains per-file SHA-256 content hashes). */
export const REMOTE_BANK_MANIFEST_NAME = 'question-bank.json';

/** app_meta keys used by the question-bank sync layer. */
export const META_KEY_BANK_HASH = 'question_bank_hash';
export const META_KEY_LAST_SYNC_AT = 'question_bank_last_sync_at';